# Form implementation generated from reading ui file 'c:\Data\Projekty\GitHub\FVE-testing-and-data-processing\dp_app\include\UIs\CSVRawDataTab.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CSVRawDataTab(object):
    def setupUi(self, CSVRawDataTab):
        CSVRawDataTab.setObjectName("CSVRawDataTab")
        CSVRawDataTab.resize(517, 386)
        self.horizontalLayout = QtWidgets.QHBoxLayout(CSVRawDataTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView = QtWidgets.QTableView(parent=CSVRawDataTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout.addWidget(self.tableView)

        self.retranslateUi(CSVRawDataTab)
        QtCore.QMetaObject.connectSlotsByName(CSVRawDataTab)

    def retranslateUi(self, CSVRawDataTab):
        _translate = QtCore.QCoreApplication.translate
        CSVRawDataTab.setWindowTitle(_translate("CSVRawDataTab", "Form"))
