# Form implementation generated from reading ui file 'c:\Data\Projekty\GitHub\FVE-testing-and-data-processing\dp_app\include\UIs\PQDiagramTab.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PQDiagramTab(object):
    def setupUi(self, PQDiagramTab):
        PQDiagramTab.setObjectName("PQDiagramTab")
        PQDiagramTab.resize(668, 745)
        self.verticalLayout = QtWidgets.QVBoxLayout(PQDiagramTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelCosPhi = QtWidgets.QLabel(parent=PQDiagramTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCosPhi.sizePolicy().hasHeightForWidth())
        self.labelCosPhi.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        self.labelCosPhi.setFont(font)
        self.labelCosPhi.setObjectName("labelCosPhi")
        self.horizontalLayout.addWidget(self.labelCosPhi)
        self.dblSpinBoxCosPhi = QtWidgets.QDoubleSpinBox(parent=PQDiagramTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dblSpinBoxCosPhi.sizePolicy().hasHeightForWidth())
        self.dblSpinBoxCosPhi.setSizePolicy(sizePolicy)
        self.dblSpinBoxCosPhi.setMaximum(1.0)
        self.dblSpinBoxCosPhi.setSingleStep(0.01)
        self.dblSpinBoxCosPhi.setObjectName("dblSpinBoxCosPhi")
        self.horizontalLayout.addWidget(self.dblSpinBoxCosPhi)
        self.horizontalSlider = QtWidgets.QSlider(parent=PQDiagramTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setSingleStep(1)
        self.horizontalSlider.setPageStep(10)
        self.horizontalSlider.setProperty("value", 50)
        self.horizontalSlider.setSliderPosition(50)
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout.addWidget(self.horizontalSlider)
        self.dialCosPhi = QtWidgets.QDial(parent=PQDiagramTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dialCosPhi.sizePolicy().hasHeightForWidth())
        self.dialCosPhi.setSizePolicy(sizePolicy)
        self.dialCosPhi.setObjectName("dialCosPhi")
        self.horizontalLayout.addWidget(self.dialCosPhi)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.PQGraph = PlotWidget(parent=PQDiagramTab)
        self.PQGraph.setMinimumSize(QtCore.QSize(0, 400))
        self.PQGraph.setMaximumSize(QtCore.QSize(16777215, 500))
        self.PQGraph.setObjectName("PQGraph")
        self.verticalLayout.addWidget(self.PQGraph)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(PQDiagramTab)
        QtCore.QMetaObject.connectSlotsByName(PQDiagramTab)

    def retranslateUi(self, PQDiagramTab):
        _translate = QtCore.QCoreApplication.translate
        PQDiagramTab.setWindowTitle(_translate("PQDiagramTab", "Form"))
        self.labelCosPhi.setText(_translate("PQDiagramTab", "cos(φ):"))
from pyqtgraph import PlotWidget
