# Form implementation generated from reading ui file 'c:\Data\Projekty\GitHub\FVE-testing-and-data-processing\dp_app\include\UIs\XYGraphTab.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_XYGraphTab(object):
    def setupUi(self, XYGraphTab):
        XYGraphTab.setObjectName("XYGraphTab")
        XYGraphTab.resize(668, 476)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(XYGraphTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBoxXData = QtWidgets.QComboBox(parent=XYGraphTab)
        self.comboBoxXData.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBoxXData.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBoxXData.setObjectName("comboBoxXData")
        self.verticalLayout.addWidget(self.comboBoxXData)
        self.comboBoxYData = QtWidgets.QComboBox(parent=XYGraphTab)
        self.comboBoxYData.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBoxYData.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBoxYData.setObjectName("comboBoxYData")
        self.verticalLayout.addWidget(self.comboBoxYData)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.XYGraph = PlotWidget(parent=XYGraphTab)
        self.XYGraph.setMaximumSize(QtCore.QSize(750, 500))
        self.XYGraph.setObjectName("XYGraph")
        self.verticalLayout_2.addWidget(self.XYGraph)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)

        self.retranslateUi(XYGraphTab)
        QtCore.QMetaObject.connectSlotsByName(XYGraphTab)

    def retranslateUi(self, XYGraphTab):
        _translate = QtCore.QCoreApplication.translate
        XYGraphTab.setWindowTitle(_translate("XYGraphTab", "Form"))
from pyqtgraph import PlotWidget
