# Form implementation generated from reading ui file 'c:\Data\Projekty\GitHub\FVE-testing-and-data-processing\dp_app\include\UIs\XYGraphTab.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_XYGraphTab(object):
    def setupUi(self, XYGraphTab):
        XYGraphTab.setObjectName("XYGraphTab")
        XYGraphTab.resize(600, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(XYGraphTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 5, 2, 1)
        self.labelDataClick1 = QtWidgets.QLabel(parent=XYGraphTab)
        self.labelDataClick1.setText("")
        self.labelDataClick1.setObjectName("labelDataClick1")
        self.gridLayout.addWidget(self.labelDataClick1, 0, 2, 1, 1)
        self.labelDataClick2 = QtWidgets.QLabel(parent=XYGraphTab)
        self.labelDataClick2.setText("")
        self.labelDataClick2.setObjectName("labelDataClick2")
        self.gridLayout.addWidget(self.labelDataClick2, 0, 3, 1, 1)
        self.comboBoxXData = QtWidgets.QComboBox(parent=XYGraphTab)
        self.comboBoxXData.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBoxXData.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBoxXData.setObjectName("comboBoxXData")
        self.gridLayout.addWidget(self.comboBoxXData, 0, 1, 1, 1)
        self.comboBoxYData = QtWidgets.QComboBox(parent=XYGraphTab)
        self.comboBoxYData.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBoxYData.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBoxYData.setObjectName("comboBoxYData")
        self.gridLayout.addWidget(self.comboBoxYData, 1, 1, 1, 1)
        self.labelXdata = QtWidgets.QLabel(parent=XYGraphTab)
        font = QtGui.QFont()
        font.setBold(True)
        self.labelXdata.setFont(font)
        self.labelXdata.setObjectName("labelXdata")
        self.gridLayout.addWidget(self.labelXdata, 0, 0, 1, 1)
        self.labelYdata = QtWidgets.QLabel(parent=XYGraphTab)
        font = QtGui.QFont()
        font.setBold(True)
        self.labelYdata.setFont(font)
        self.labelYdata.setObjectName("labelYdata")
        self.gridLayout.addWidget(self.labelYdata, 1, 0, 1, 1)
        self.labelDataClick3 = QtWidgets.QLabel(parent=XYGraphTab)
        self.labelDataClick3.setText("")
        self.labelDataClick3.setObjectName("labelDataClick3")
        self.gridLayout.addWidget(self.labelDataClick3, 0, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelMeasDate = QtWidgets.QLabel(parent=XYGraphTab)
        font = QtGui.QFont()
        font.setBold(True)
        self.labelMeasDate.setFont(font)
        self.labelMeasDate.setObjectName("labelMeasDate")
        self.horizontalLayout.addWidget(self.labelMeasDate)
        self.labelMeasDateValue = QtWidgets.QLabel(parent=XYGraphTab)
        font = QtGui.QFont()
        font.setBold(False)
        self.labelMeasDateValue.setFont(font)
        self.labelMeasDateValue.setText("")
        self.labelMeasDateValue.setObjectName("labelMeasDateValue")
        self.horizontalLayout.addWidget(self.labelMeasDateValue)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.XYGraph = PlotWidget(parent=XYGraphTab)
        self.XYGraph.setMinimumSize(QtCore.QSize(0, 400))
        self.XYGraph.setMaximumSize(QtCore.QSize(16777215, 500))
        self.XYGraph.setObjectName("XYGraph")
        self.verticalLayout.addWidget(self.XYGraph)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem3)

        self.retranslateUi(XYGraphTab)
        QtCore.QMetaObject.connectSlotsByName(XYGraphTab)

    def retranslateUi(self, XYGraphTab):
        _translate = QtCore.QCoreApplication.translate
        XYGraphTab.setWindowTitle(_translate("XYGraphTab", "Form"))
        self.labelXdata.setText(_translate("XYGraphTab", "Data on X axis:"))
        self.labelYdata.setText(_translate("XYGraphTab", "Data on Y axis:"))
        self.labelMeasDate.setText(_translate("XYGraphTab", "Measurement date:"))
from pyqtgraph import PlotWidget
